import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <header>
          <nav>
            <ul>
              <li className="logo">PET SHOP</li>
              <li><a href="http://localhost:3000">home</a></li>
              <li><a href="http://localhost:3000/about">about</a></li>
              <li><a href="http://localhost:3000/contact">Contact</a></li>
            </ul>
          </nav>
        </header>

        {children}

        </body>
    </html>
  );
}
